baseURL = "http://voidmain.guru/"
languageCode = "zh-cn"
theme = "hello-friend-ng"

googleAnalytics = ""

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # Metadata mostly used in document's head
  description = "Homepage and blog by void main"
  keywords = "homepage, blog, development, programming, programmer, java"
  images = [""]

  # Directory name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # Default theme "light" or "dark"
  defaultTheme = "dark"

  # Social icons
  [[params.social]]
    name = "email"
    url  = "mailto:voidmain1313113@gmail.com"

  [[params.social]]
    name = "github"
    url  = "https://github.com/void-main"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/void-main/"

  [[params.social]]
    name = "twitter"
    url  = "https://twitter.com/voidmain13"
  
[languages]
  [languages.en]
    title = "Deep into Void"
    subtitle = "A homepage & blog by void-main"
    keywords = "void-main, developer"
    copyright = 'void-main'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "Deep into Void"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

# And you can even create generic menu
[menu]
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about"
  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "https://blog.voidmain.guru/"
  [[menu.main]]
    identifier = "video"
    name       = "Video"
    url        = "https://space.bilibili.com/425568"
  [[menu.main]]
    identifier = "photo"
    name       = "Photo"
    url        = "https://500px.com/void-main"